site_url: https://lola-communities.vercel.app
display_url: https://lola-communities.vercel.app

backend:
  name: github
  repo: lolaent/lola-communities
  branch: main
  base_url: https://lola-communities.vercel.app
  auth_endpoint: api/begin
  commit_messages:
    create: "feat: add {{collection}} {{slug}}"
    update: "fix: update {{collection}} {{slug}}"
    delete: "fix: remove {{collection}} {{slug}}"
    uploadMedia: "feat: add media {{path}}"
    deleteMedia: "fix: remove media {{path}}"
local_backend: true
publish_mode: editorial_workflow

media_folder: public/img
public_folder: img

media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: dzypedzhp
    api_key: 866969769554875

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        preview_path: "/"
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown"}
      - label: "Starting a Community"
        name: "starting-a-community"
        file: "content/starting-a-community.md"
        preview_path: "/"
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown"}
  - name: "communities"
    label: "Communities"
    label_singular: "Community"
    description: "Individual community pages"
    folder: "content/communities"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Purpose", name: "body", widget: "markdown"}
      - label: "Email"
        name: "email"
        widget: "string"
        required: false
        pattern:
          - '^$|^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$'
          - "Must be a valid email address"
      - label: "Slack"
        name: "slack"
        widget: "string"
        required: false
        pattern:
          - '^$|^((([A-Za-z]{3,9}:(?:\/\/)?)(?:[\-;:&=\+\$,\w]+@)?[A-Za-z0-9\.\-]+|(?:www\.|[\-;:&=\+\$,\w]+@)[A-Za-z0-9\.\-]+)((?:\/[\+~%\/\.\w\-_]*)?\??(?:[\-\+=&;%@\.\w_]*)#?(?:[\.\!\/\\\w]*))?)$' # source http://urlregex.com
          - "Must be a valid url"
