site_url: https://lola-communities.vercel.app
display_url: https://lola-communities.vercel.app

backend:
  name: github
  repo: lolaent/lola-communities
  branch: main
  base_url: https://lola-communities.vercel.app
  auth_endpoint: api/begin
  commit_messages:
    create: "feat: add {{collection}} {{slug}}"
    update: "fix: update {{collection}} {{slug}}"
    delete: "fix: remove {{collection}} {{slug}}"
    uploadMedia: "feat: add media {{path}}"
    deleteMedia: "fix: remove media {{path}}"
local_backend: true
publish_mode: editorial_workflow

media_folder: public/img
public_folder: img

media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: lolatech
    api_key: 277628224366354

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/pages/home.md"
        preview_path: "/"
        fields:
          - {label: "Small Title", name: "stitle" , widget: "string", required: false}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Intro Text", name: "intro", widget: "markdown"}
          - {label: "CoP Section Title", name: "copTitle", widget: "string"}
          - {label: "Events Section Title", name: "eventsTitle", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime" , required: false}
      - label: "Starting a Community"
        name: "starting-a-community"
        file: "content/pages/starting-a-community.md"
        preview_path: "/"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime" }
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "communities"
    label: "Communities"
    label_singular: "Community"
    description: "Individual community pages"
    folder: "content/communities"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Intro text", name: "intro", widget: "markdown", required: false}
      - label: "Events"
        name: "events"
        widget: "list"
        required: false
      - label: Members   
        name: "members"
        widget: "list" 
        required: false
      - {label: "CTA to Join", name: "ctaJoin", widget: "markdown", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - label: "Email"
        name: "email"
        widget: "string"
        required: false
        pattern:
          - '^$|^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$'
          - "Must be a valid email address"
      - label: "Slack"
        name: "slack"
        widget: "string"
        required: false
        pattern:
          - '^$|^((([A-Za-z]{3,9}:(?:\/\/)?)(?:[\-;:&=\+\$,\w]+@)?[A-Za-z0-9\.\-]+|(?:www\.|[\-;:&=\+\$,\w]+@)[A-Za-z0-9\.\-]+)((?:\/[\+~%\/\.\w\-_]*)?\??(?:[\-\+=&;%@\.\w_]*)#?(?:[\.\!\/\\\w]*))?)$' # source http://urlregex.com
          - "Must be a valid url"
  - name: "events"
    label: "Events"
    label_singular: "Event"
    description: "Individual event pages"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Host", name: "host", widget: "string"}
      - {label: "Content", name: "content", widget: "markdown" , required: false}
