name: Lint and Test
on:
  push: 
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Yarn install (with caching)
      uses: bahmutov/npm-install@v1.4.5
    - name: Lint
      run: yarn lint --if-present
    - name: Test
      run: yarn test --if-present
