name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: CI

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Yarn install (with caching)
        uses: bahmutov/npm-install@v1.6.2
      - name: Lint
        run: yarn lint
